image: node:latest

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

before_script:
  - npm install

stages:
  - build
 
Compile:
  stage: build
  script:
    - npm run build
    - npm run package
  artifacts:
      paths:
        - ical-to-json_1.0.0.zip
